### ISSUE TITLE
C^1 or C'

### ISSUE THREAD

**Issue by bimmlerd** [pennatil/Analysis-Notes#53]
We have a bit of an issue here, is the correct class C' or C^1?
We use C' relatively consistently within the doc, but at some places it's even `\subset '`...
example include
[Chap8](https://github.com/pennatil/Analysis-Notes/blob/master/Tex/Chapters/Chapter_8.tex#L711)...

**Comment by limenet** [comment]
I already discussed this with @pennatil a bit. IMO it is C^1, because it is referring to the functions which are differentiable (at least) once. Prof. Immamoglu obviously uses the American way of writing numbers where a "1" looks like a "|". And here's [Wikipedia](http://en.wikipedia.org/wiki/Differentiability_class) for reference.

**Comment by pennatil** [comment]
We did discuss it, but I'm still not a 100% sure about it...

**Comment by bimmlerd** [comment]
The reasons @limenet gives seem pretty plausible to me, I'll change what I can find to C^1.
Thanks.

**Comment by pennatil** [comment]
Ok, then it's decided: We'll change everything to C^1
