### ISSUE TITLE
Chapters 1,3,6,8: ∞]

### ISSUE THREAD

**Issue by limenet** [pennatil/Analysis-Notes#67]
There are in total four occurrences of

``` tex
\infty\rbrack
```

which means ∞ is included in the interval which is by definition not possible (at least what I've been taught) and the usual notation in the scripts is ∞). Since I don't know how I'd have to change this to be compliant with the styling/TeX itself, I ask someone else to please do this change. Thanks!

**Comment by bimmlerd** [comment]
Heh, good catch :+1: 
Easy to fix, replace with `\infty)`.

**Comment by limenet** [comment]
Okay, wasn't sure, since sometimes I saw a \right switch before a parenthesis... Thanks!

**Comment by bimmlerd** [comment]
The `\right)` is used in pair with a `\left(` and makes LaTeX scale the parentheses. So for example if you have a sum in there, it looks like this
![image](https://cloud.githubusercontent.com/assets/7094770/3761075/fd543628-1883-11e4-9958-f0e0192f8594.png)
rather than like this

![image](https://cloud.githubusercontent.com/assets/7094770/3761083/1b7a7630-1884-11e4-8eee-7122335a99e4.png)

**Comment by bimmlerd** [comment]
@limenet Can't find the one in chapter 3, could you point me to the right line?
Edit: nevermiind, I found it^^

**Comment by limenet** [comment]
@bimmlerd thanks for pointing out the LaTeX parentheses scaling!
